### PR TITLE
Release candidate for beta UI v2 0.4

### PR DESCRIPTION
**Pull request by utiq**
The fast-forward phases selector was implemented.
I also refactored up the WDUI component separating the position components into smaller files so it is easier to maintain.

fast-forward

Here there is the laptop version

Filmage 2022-07-19_185132

### CODE REVIEW

**Comment by adamlerer** [comment]
Wow, this is a big UI change!

Initial things i noticed:
- Why do we have the country here when it's already right above? 
image
- Why did every icon move to a new place?
- Why is the phase listed in the top-left and bottom right?
- In bottom right, can we have the season too? (i.e. S1902M instead of S1902)
- In some places it looks like you're using "Autumn" instead of "Fall". Can we use "Fall" everywhere? 
image
- What does the button in top-right do?
- Can you add a screencast of the UI on a laptop?

**Comment by utiq** [comment]
@adamlerer regarding your questions
Why do we have the country here when it's already right above?

Those are updates that Dirk included in the last UI version. I'm not sure why the name of the country appears in the black box again but it makes sense to me. I'm thinking that a new user/player wouldn't get confused.

image

Why did every icon move to a new place?
I'm not sure, ask Dirk, he might have a good explanation. So far, the changes make a lot of sense to me.

Why is the phase listed in the top-left and bottom right?
I think because at the beginning S1901 wouldn't make too much sense for a new player.

In bottom right, can we have the season too? (i.e. S1902M instead of S1902)
What does the M stand for?

In some places it looks like you're using "Autumn" instead of "Fall". Can we use "Fall" everywhere? Also, show the phase (Movement vs Retreat)?
Can you point where exactly? you mean you want to replace the word "Autumn" for "Fall"?

This is how the top-left black box will also look like (not implemented in this PR update)
image

What does the button in top-right do? - Can you add a screencast of the UI on a laptop?
it takes you to the home page. I added a screencast of the laptop version to the description

**Comment by adamlerer** [comment]
Why are 2500 lines of changes going into a PR called "Fast-forward/fast-rewind buttons"? It seems like this is just a branch with the new version of the UI...

**Comment by utiq** [comment]
> Why are 2500 lines of changes going into a PR called "Fast-forward/fast-rewind buttons"? It seems like this is just a branch with the new version of the UI...

It's a branch with the new version of the UI. My plan was only to add the fast-forward/fast-review UI that Dirk designed but because the design required a files/folders restructuration, I just started adding everything in that PR. It would be nice if we could merge it as soon as possible so we can start merging out of kestas/webDiplomacy

**Comment by adamlerer** [comment]
Yep, would be great to merge ASAP. I think we should name this branch with a UI version number, and then don't commit any new features to it, just bugfixes from internal user testing. Then later this week you can send a PR to Kestas with this new version?

**Pull request merged**
