### PR TITLE
Docker configuration

### PR DESCRIPTION
**Pull request by utiq**
It was a previous docker-compose configuration already created by [kestasjk](https://github.com/kestasjk) for development purposes. I modified it so we can run the beta in the same URL and we avoid having 2 repositories.

### CODE REVIEW

**Review by adamlerer — COMMENTED** [review]
Nice! Does this work with `npm start`? I remember getting rid of the BASE_URL stuff because it was incompatible with `npm start`...

**Comment by utiq** [comment]
@adamlerer yes, as you can see in line 62-63, every time is started it runs `npm install and npm start`

image

**Comment by adamlerer** [comment]
Cool. But my question was a bit different: The app wasn't working for me under `npm start` until I removed the BASE_URL stuff because it was pointing at the wrong backend or something (it wasn't able to load data from api.php). Have you checked that you can run the app through localhost:3000 under this configuration?

**Comment by utiq** [comment]
@adamlerer @lightvector I put back the proxy in package.json in the latest commit so it can work with relative paths (notice I changed the default port to 43000)

I think would be a good idea to use BASE_URL since I see that was [kestasjk](https://github.com/kestasjk)'s intention. I see he created the API to be able to authenticate using a bearer token linked to a user https://github.com/adamlerer/webDiplomacy/blob/main/api.php#L1370-L1422

If we wanted to add the CORS config, we would add these 2 lines in header.php
```
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Credentials: true");
```

Anyways, we can leave the CORS stuff and security for later.
Now you should be able to start the react app using `npm run start`. At the same time, you can start the app and server in the docker way by doing `docker-compose up`

**Pull request merged**
